Fix permission denied error at checkout step in OSS CI (#2204)
Summary:
OSS CI jobs often failed at checkout step with error
`Error: File was unable to be removed
Error: EACCES: permission denied, rmdir '/home/ec2-user/actions-runner/_work/FBGEMM/FBGEMM/3'`

This is because during the build process of one job, the script executes installations of dependencies in the folder under different user (ie.e,`root` in Nova job). In the subsequent job run on the same runner, `ec2-user` tries to clean up the folder but unable able to, causing the permission denied error.
For example, https://github.com/pytorch/FBGEMM/actions/runs/7151275180/job/19475677899 all failed because the runners were used to build wheel in the previous job, i.e. https://github.com/pytorch/FBGEMM/actions/runs/7150909712/job/19474677106.

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/2204

Reviewed By: q10, huydhn

Differential Revision: D52054787

fbshipit-source-id: f363e1c948ffe9b95f1d384bbca521faa78c12b9