Fix numpy issue libstdc++.so.6 not found (#3080)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/175

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/3080

`numpy` package on `conda-forge` causes error:
```
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
```
Remove installation from `conda` and let it be installed by `pip`.
https://github.com/pytorch/FBGEMM/actions/runs/10712252806/job/29702380694

Full error below:
```
Please note and check the following:

  * The Python version is: Python3.9 from "/__w/_temp/conda_environment_10708405243/bin/python"
  * The NumPy version is: "2.0.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__w/_temp/conda_environment_10708405243/lib/python3.9/site-packages/numpy/_core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/__w/FBGEMM/FBGEMM/pytorch/FBGEMM/fbgemm_gpu/setup.py", line 21, in <module>
    import torch
  File "/__w/_temp/conda_environment_10708405243/lib/python3.9/site-packages/torch/__init__.py", line 1707, in <module>
    from torch import storage as storage  # usort: skip
  File "/__w/_temp/conda_environment_10708405243/lib/python3.9/site-packages/torch/storage.py", line 23, in <module>
    import numpy as np
  File "/__w/_temp/conda_environment_10708405243/lib/python3.9/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

https://github.com/pytorch/FBGEMM/actions/runs/10708405243/job/29690649284

Reviewed By: q10, sryap

Differential Revision: D62210034