Use fbgemm_fml_flags and add fbgemm_sve guard (#4948)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/1977

Add a missing part in https://github.com/pytorch/FBGEMM/issues/4942 .
I also fix another aarch64 issue on PyTorch CI:
```
/var/lib/jenkins/workspace/third_party/fbgemm/include/fbgemm/./Utils.h:26:10: fatal error: arm_neon_sve_bridge.h: No such file or directory
   26 | #include <arm_neon_sve_bridge.h> // manual
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
[ARM documentation](https://developer.arm.com/documentation/110065/0100/Software-codec-optimization/Compiler-recommendations) says:

SVE and SVE2 feature paths in libaom, libvpx, and x265 require the intrinsics declared in arm_neon_sve_bridge.h. This header file is available in the following releases:

Clang 17 and later.
GCC 14 and later.

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/4948

Reviewed By: cthi

Differential Revision: D83578552

Pulled By: q10

fbshipit-source-id: 13b07cbb68ec7b233488a1958d86510b8828a52f