Downgrade googletest to an older version
Summary:
As title. For the previous google test version, it can pass the OSS unit tests in the PR (e.g., https://github.com/pytorch/FBGEMM/pull/473, check the green check symbol), but failed the CircleCI unit tests when committing to the trunk:
https://app.circleci.com/pipelines/github/pytorch/FBGEMM/95/workflows/f13cd5ce-8787-4564-a96d-2d7b2597b67f/jobs/476

```
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h: At global scope:
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:1239:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
 template <size_t... Idx, typename... T>
                     ^
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:1239:34: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
 template <size_t... Idx, typename... T>
```

Maybe due to c++11 support?

Checking the current CMakeLists.txt in google test, it doesn't specify c++11 support.

This Diff reverts to an older version of google test commit (still newer than the old Sept 2018 version of google test) which includes "GTEST_SKIP" supports:

```
set(GOOGLETEST_VERSION 1.10.0)

if (CMAKE_VERSION VERSION_LESS "3.1")
  add_definitions(-std=c++11)
else()
  set(CMAKE_CXX_STANDARD 11)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  if(NOT CYGWIN)
    set(CMAKE_CXX_EXTENSIONS OFF)
  endif()
endif()
```

Differential Revision: D25801335

fbshipit-source-id: 093d83e2de9874ef55ad637b28cd025eae0a97cf