Fix permission denied error at checkout step in OSS CI (#2204)
Summary:
OSS CI jobs often failed at checkout step with error 
`Error: File was unable to be removed
Error: EACCES: permission denied, rmdir '/home/ec2-user/actions-runner/_work/FBGEMM/FBGEMM/3'`

This is because during the build process of one job, the script executes installations of dependencies in the folder under different user (e.g.,`root` in Nova job). In the subsequent job run on the same runner, `ec2-user` tries to clean up the folder but unable able to, causing the permission denied error.

Thank you huydhn for looking into the log and suggesting the fix.


Differential Revision: D52054787