Fix build-time error for tbb in CentOS. (#5497)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/2489

avoid including tbb-2020.3-9.el9.x86_64 header (on CentOS) that triggers a build-time error when using clang++.
CentOS packages TBB 2020.3 version, which has a bug in the header file and triggers the following error.
```
/usr/include/tbb/task.h:590:28: error: in-class initializer for static data member is not a constant expression
  590 |     static const kind_type binding_completed = kind_type(bound+1);
```
Ubuntu packages TBB 2021.11 version and doesn't have this issue.


Reviewed By: q10

Differential Revision: D97379321

Pulled By: spcyppt