Skip InputCombineTest for ROCm on OSS CI (#2229)
Summary:
InputCombineTest fails or hangs on OSS CI. Skip until it is fixed.
```
E       RuntimeError: HIP error: invalid device function
E       HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E       For debugging consider passing HIP_LAUNCH_BLOCKING=1.
E       Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```
- https://github.com/pytorch/FBGEMM/actions/runs/7183699723/job/19569423894
- https://github.com/pytorch/FBGEMM/actions/runs/7077790129/job/19262521876

```
Error: The action has timed out.
```
- https://github.com/pytorch/FBGEMM/actions/runs/7248322447/job/19744609424
- https://github.com/pytorch/FBGEMM/actions/runs/7222269614/job/19679475071

Differential Revision: D52280122

Pulled By: spcyppt