Back out "Improve AVX detection" (#5204)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/2201

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/5204

The original diff appears to break `import fbgemm_gpu` in ROCm containers with the error message below:

```
OSError: /workspace/FBGEMM/fbgemm_gpu/fbgemm_gpu/fbgemm.so: undefined symbol: _ZN6fbgemm49Fused8BitRowwiseQuantizedSBFloatToFloatOrHalfAvx2ItLb1ELb1EEEvPKhmiPT_
```

It was likely not caught in CI due to ROCm machines being down at the moment (https://github.com/pytorch/pytorch/issues/169684)

Original commit changeset: e095f4d42664

Original Phabricator Diff: D88299401

Reviewed By: cthi

Differential Revision: D88759928

fbshipit-source-id: 587d0444ec28ffcb0b02dd2a634bcbc16f0f1582