fbgemm::batch_index_select and fbgemm:: keyed_jagged_index_select (#2438)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/2438

# batch_index_select_dim0
* source of truth forthe function in [GPU CPP](https://fburl.com/code/8nhxisy1)
```
Tensor batch_index_select_dim0_gpu(
    Tensor inputs,
    Tensor indices,
    std::vector<int64_t> input_num_indices,
    std::vector<int64_t> input_rows,
    std::vector<int64_t> input_columns,
    // Permute dim 0 and 1 of the output tensor
    const bool permute_output_dim_0_1)
```

* test data generation example in [test_batch_index_select_dim0](https://fburl.com/code/df4s0ml9)
```
output_ref = [
    input.index_select(dim=0, index=index).flatten()
    for input, index in zip(inputs, indices)
]

output_test = torch.ops.fbgemm.batch_index_select_dim0(
    concat_inputs,
    concat_indices,
    input_num_indices,
    input_rows,
    input_columns,
    permute_output_dim_0_1,
)
```

# keyed_jagged_index_select_dim1
* input argument registration in [sparse_ops_cpu.cpp](https://fburl.com/code/a11zx1nv)
```
  m.def(
      "keyed_jagged_index_select_dim1(Tensor values, Tensor lengths, Tensor offsets, Tensor indices, SymInt batch_size, Tensor? weights=None, SymInt? selected_lengths_sum=None) -> Tensor[]");
```

* source of truth for the function in [GPU CUDA](https://fburl.com/code/h536wn8y)
```
__global__ void keyed_jagged_index_select_dim1_kernel(
    at::PackedTensorAccessor64<scalar_t, 1, at::RestrictPtrTraits> output,
    at::PackedTensorAccessor64<weight_t, 1, at::RestrictPtrTraits>
        output_weights,
    const at::PackedTensorAccessor64<scalar_t, 1, at::RestrictPtrTraits> input,
    const at::PackedTensorAccessor64<weight_t, 1, at::RestrictPtrTraits>
        weights,
    const at::PackedTensorAccessor32<offset_t, 1, at::RestrictPtrTraits>
        input_offsets,
    const at::PackedTensorAccessor32<index_t, 1, at::RestrictPtrTraits> indices,
    const at::PackedTensorAccessor32<offset_t, 1, at::RestrictPtrTraits>
        output_offsets,
    const int num_batches,
    const int input_batch_size)
```

* [test_keyed_jagged_index_select_dim1](https://fburl.com/code/rrxp6osc)
```
output_ref = []
output_weight_ref = []
for k in range(num_batches):
    key_lengths = lengths[k * input_batch_size : (k + 1) * input_batch_size]
    start_offset = offsets[k * input_batch_size]
    end_offset = offsets[(k + 1) * input_batch_size]
    key_values = values_ref[start_offset:end_offset].view(-1, 1)
    output_ref.append(
        torch.ops.fbgemm.jagged_index_select(key_values, key_lengths, indices)[
            0
        ].view(-1)
    )
    if has_weights:
        # pyre-ignore[16]
        key_weights = weights[start_offset:end_offset].view(-1, 1)
        output_weight_ref.append(
            torch.ops.fbgemm.jagged_index_select(
                key_weights, key_lengths, indices
            )[0].view(-1)
        )

output_ref = torch.concat(output_ref)
```

# Notes
* compile works for `batch_index_select_dim0` (please see the test plan), but failed for `test_keyed_jagged_index_select_dim1`. It's unlikely a bento setup issue. The error message complains "data dependent operator"
```
data dependent operator: aten._local_scalar_dense.default; to enable, set torch._dynamo.config.capture_scalar_outputs = True

from user code:
   File "/tmp/ipykernel_1445682/1191350425.py", line 2, in <lambda>
    fn = lambda: torch.ops.fbgemm.keyed_jagged_index_select_dim1(

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```
* after going through the stack trace, it could be due to the output Tensor size = `selected_lengths_sum`, which is an optional argument, and it will be calculated based on the input tensor `lengths` when not provided.

* The diff test also failed: 1) github-export-checks, 2) operator does not exist. Not sure if these failures are expected or not.
```
if you fixed the below errors and this error is still here, please rerun this job (github-export-checks) manually.

No GitHub pull request(s) for pytorch/FBGEMM were found linked for your diff. Please export your diff here: https://our.intern.facebook.com/.../preview/D54669445/.
```

```
RuntimeError: operator fbgemm::batch_index_select_dim0 does not exist
2024-03-09T19:45:33.412907Z  INFO re_gpu_analyzer: Command exited with exit code cmd_status=ExitStatus(unix_wait_status(256))
2024-03-09T19:45:33.412954Z  WARN re_gpu_analyzer: detected_problem="The command is running on a worker with dedicated GPUs but hasn't used any during its execution."
```
* it really took some time and efforts to figure out the definition/expectation of these two functions, especially the KeyedJaggedTensor, most of my understandings are from reading the two test_functions (really appreciate it!). Curious if there is any design doc for these functions.

# Readings
* [KeyedJaggedTensor](https://pytorch.org/torchrec/torchrec.sparse.html) for [minibatch](https://pytorch.org/tutorials/intermediate/torchrec_tutorial.html#representing-minibatches-with-keyedjaggedtensor)
> We need an efficient representation of multiple examples of an arbitrary number of entity IDs per feature per example. In order to enable this “jagged” representation, we use the TorchRec datastructure KeyedJaggedTensor (KJT).

> Let’s take a look at how to lookup a collection of two embedding bags, “product” and “user”. Assume the minibatch is made up of three examples for three users. The first of which has two product IDs, the second with none, and the third with one product ID.
|------------|------------|
| product ID | user ID    |
|------------|------------|
| [101, 202] | [404]      |
| []         | [505]      |
| [303]      | [606]      |
|------------|------------|
```
mb = torchrec.KeyedJaggedTensor(
    keys = ["product", "user"],
    values = torch.tensor([101, 202, 303, 404, 505, 606]).cuda(),
    lengths = torch.tensor([2, 0, 1, 1, 1, 1], dtype=torch.int64).cuda(),
)

print(mb.to(torch.device("cpu")))
```

* [impl_abstract](https://pytorch.org/docs/stable/library.html#torch.library.impl_abstract)
> An “abstract implementation” specifies the behavior of this operator on Tensors that carry no data. Given some input Tensors with certain properties (sizes/strides/storage_offset/device), it specifies what the properties of the output Tensors are.

> The abstract implementation has the same signature as the operator. It is run for both **FakeTensors** and **meta tensors**. To write an abstract implementation, assume that all Tensor inputs to the operator are regular CPU/CUDA/Meta tensors, but they do not have storage, and you are trying to return regular CPU/CUDA/Meta tensor(s) as output. The abstract implementation must consist of only PyTorch operations (and may not directly access the storage or data of any input or intermediate Tensors).

* [fake tensor](https://pytorch.org/docs/stable/torch.compiler_fake_tensor.html)
> When doing Dynamo symbolic evaluation and compiler passes, we often want to be able to run tensor operations to understand what output sizes/dtypes/devices are, without actually running those operations (or trashing preexisting tensors)...
A fake tensor is like a real tensor in all respects, except that it doesn’t actually have any data. For example, when we do Dynamo tracing, we need to trace through user Tensor code and answer questions about intermediates.

> A meta tensor is a tensor with device=’meta’. This is actually a lot of what you want for fake tensor, but meta tensors don’t model devices, and sometimes stride behavior varies depending on your device, so fake tensors really can get a lot more accurate info this way. Also, meta tensors are “global” (they exist on their own, similar to how a CPU/CUDA tensor exist on their own), whereas fake tensors are scoped to a FakeTensorMode.

Reviewed By: ezyang

Differential Revision: D54669445

fbshipit-source-id: 2d3d0f6e7b191d3822442be4396f0c7ff699155f