Fix OSS build failure due to approx sgd
Summary:
Resolve OSS failure:
```
======================================================================
ERROR: test_backward_sgd (__main__.SplitTableBatchedEmbeddingsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/split_table_batched_embeddings_test.py", line 444, in test_backward_sgd
    T=st.integers(min_value=1, max_value=5),
  File "/home/jianyuhuang/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 1162, in wrapped_test
    raise the_error_hypothesis_found
  File "test/split_table_batched_embeddings_test.py", line 615, in test_backward_sgd
    if not weighted
  File "/home/jianyuhuang/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 879, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jianyuhuang/Work/Github/FBGEMM/fbgemm_gpu/fbgemm_gpu/split_table_batched_embeddings_ops.py", line 503, in forward
    return invokers.lookup_approx_sgd.invoke(common_args, self.optimizer_args)
AttributeError: module 'fbgemm_gpu.split_embedding_codegen_lookup_invokers' has no attribute 'lookup_approx_sgd'
```

Differential Revision: D27245407

fbshipit-source-id: 9f2d5a298bcb0b49159128e785d37d3f93ec67c9