Add hash_zch_identities to SplitTableBatchedEmbeddingBagsCodegen forward (#5144)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/5144

X-link: https://github.com/facebookresearch/FBGEMM/pull/2143

We need the signature change in tbe for hash_zch_identities tracking to work e2e https://fburl.com/mlhub/gj74u04u
```
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torchrec/distributed/embedding_lookup.py", line 710, in forward
    lookup = emb_op(features)
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torch/nn/modules/module.py", line 1783, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torch/nn/modules/module.py", line 1794, in _call_impl
    return forward_call(*args, **kwargs)
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torchrec/distributed/batched_embedding_kernel.py", line 2695, in forward
    return self.emb_module(
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torch/nn/modules/module.py", line 1783, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torch/nn/modules/module.py", line 1889, in _call_impl
    return inner()
  File "/dev/shm/uid-99/0e23d97f-seed-nspid4026559588_cgpid7415242-ns-4026559309/torch/nn/modules/module.py", line 1837, in inner
    result = forward_call(*args, **kwargs)
TypeError: SplitTableBatchedEmbeddingBagsCodegen.forward() got an unexpected keyword argument 'hash_zch_identities'
```

Reviewed By: chouxi

Differential Revision: D87244481

fbshipit-source-id: f7c2a4e70ee521dc47d47ec2cc304d778c8a2ddc