Fix the OSS build failure
Summary:
As title. It can pass the OSS unit tests in the PR (e.g., https://github.com/pytorch/FBGEMM/pull/473, check the green check symbol), but failed the CircleCI unit tests when committing to the trunk:
https://app.circleci.com/pipelines/github/pytorch/FBGEMM/95/workflows/f13cd5ce-8787-4564-a96d-2d7b2597b67f/jobs/476

```
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h: At global scope:
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:1239:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
 template <size_t... Idx, typename... T>
                     ^
/root/project/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:1239:34: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
 template <size_t... Idx, typename... T>
```

Maybe due to c++11 support?

Differential Revision: D25799546

fbshipit-source-id: ed47cb834e600173872d1aa0da164ba8f622f66a