Fix GCC pragma errors (#5167)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/2182

Enabling FBGEMM aarch64 builds on Pytorch failed with
```
/var/lib/jenkins/workspace/third_party/fbgemm/src/QuantUtilsNeon.cc:73: error: ignoring ‘#pragma GCC novector’ [-Werror=unknown-pragmas]
   73 | #pragma GCC novector unroll 0
      |
```
Because `novector` was introduced in GCC 14, this PR fixes it.

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/5167

Reviewed By: cthi

Differential Revision: D88205502

Pulled By: q10

fbshipit-source-id: 40dc1c2464ba0ef00cd613649b76c13f52d2e481