Fix bf16i4bf16 unit test failure
Summary:
Revert the changes on bf16i4bf16 GEMM routine: causing some errors in unit test.

https://www.internalfb.com/intern/test/562950059123389/

```
_h100#link-tree/gen_ai/llm_inference/fb/llm/llama_layers.py", line 352, in matmul_nt
    return torch.ops.fbgemm.bf16i4bf16_rowwise(x, w.weight, w.scale, w.zero_point)
  File "/re_cwd/buck-out/v2/gen/fbcode/c2e398f2bd191d93/gen_ai/llm_inference/fb/llm/__llama_tests_h100__/llama_tests_h100#link-tree/torch/_ops.py", line 1124, in __call__
    return self_._op(*args, **(kwargs or {}))
RuntimeError: cutlass cannot implement
```

Reviewed By: jiawenliu64

Differential Revision: D59924899