Fix faketensor error when dev_weights is undefined. (#837)
Summary:
X-link: https://github.com/pytorch/FBGEMM/pull/3755

Pull Request resolved: https://github.com/facebookresearch/FBGEMM/pull/837

test_faketensor__test_backward_adagrad_fp32_pmSUM failed with
```
RuntimeError: tensor does not have a device
```
`dev_weights` is found to be`undefined`, hence calling `dev_weights.options()` causes the error.

Reviewed By: sryap

Differential Revision: D70309633

fbshipit-source-id: ae81cebe052e765e2cdba76f7f02f6bfe5569f24