Fix PT2 compliant opcheck tests (#492)
Summary:
Pull Request resolved: https://github.com/facebookresearch/FBGEMM/pull/492

X-link: https://github.com/pytorch/FBGEMM/pull/3404

Add decorator to skip PT2 compliant opcheck tests.

```
AssertionError: op 'fbgemm::split_embedding_codegen_lookup_rowwise_adagrad_function' was tagged with torch.Tag.pt2_compliant_tag but it failed some of the generated opcheck tests (['BackwardAdagradGlobalWeightDecay.test_faketensor__test_backward_adagrad_global_weight_decay',
```
This is due to faketensor test being added to the failure_dict.

Faketensor tests fail because it expect all tensors to be on the same device, whereas we set learning_rate_tensor to be on CPU to avoid D->H sync as it will be converted to float for the kernel.

Reviewed By: q10

Differential Revision: D66346179

fbshipit-source-id: 8b0784071a9845a33ba3a75ab8a486d727a92672