fused moe fix (#4534)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/4534

X-link: https://github.com/facebookresearch/FBGEMM/pull/1579

A number of changes on CK header that we need downstream fixes:
* local token was added to MoeSortingProblemEx: https://github.com/ROCm/composable_kernel/blob/develop/include/ck_tile/ops/fused_moe/kernel/moe_sorting_problem.hpp#L48
* MeshType_ was added to MoeSortingProblemMp: https://github.com/ROCm/composable_kernel/blob/develop/include/ck_tile/ops/fused_moe/kernel/moe_sorting_problem.hpp#L56
* MOE_SORTING_FMOE_2D_BUF was added which I just turn off for now
```
In file included from buck-out/v2/gen/fbcode/de5ab6968d300cd2/deeplearning/fbgemm/fbgemm_gpu/experimental/gen_ai/src/quantize/ck_extensions/__ck_fused_moe_hipify_gen__/out/fused_moe/instances/fused_moesorting_api.hip:4:
In file included from fbcode/deeplearning/fbgemm/fbgemm_gpu/experimental/gen_ai/src/quantize/ck_extensions/fused_moe/fused_moesorting.hpp:8:
In file included from third-party/rocm_composable_kernel/include/ck_tile/ops/fused_moe.hpp:9:
third-party/rocm_composable_kernel/include/ck_tile/ops/fused_moe/kernel/moe_sorting_kernel.hpp:2100:11: error: no member named 'moe_buf_elem_bytes' in 'ck_tile::MoeSortingMultiPhaseKernel_P2<ck_tile::MoeSortingProblemMp<int, float, int, 1, false, false>>::Kargs'
 2100 |         k.moe_buf_elem_bytes = h.moe_buf_elem_bytes;
      |         ~ ^
```

Reviewed By: zjing14

Differential Revision: D78679653