fix shared lib build
Summary:
This fixes shared lib build which was failing with the following error.
```
MakeFiles/TransposeTest.dir/TransposeTest.cc.o: In function `TransposeTest_TransposeTest_Test::TestBody()':
TransposeTest.cc:(.text+0x8ec): undefined reference to `fbgemm::transpose_simd(int, int, float const*, int, float*, int)'
collect2: error: ld returned 1 exit status
```

Reviewed By: jspark1105

Differential Revision: D18033440

fbshipit-source-id: fcc65aa3fba4d26f7cf201c16578e554cd016974