Fix OSS build (#635)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/635

Fix OSS build issue on `indices_remap_avx512` routine, which is introduced by  https://github.com/pytorch/FBGEMM/pull/607/files .

```
>> import torch
>> torch.ops.load_library("fbgemm_gpu_py.so")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/samiw1/anaconda3/envs/sami_env/lib/python3.8/site-packages/torch/_ops.py", line 107, in load_library
    ctypes.CDLL(path)
  File "/home/samiw1/anaconda3/envs/sami_env/lib/python3.8/ctypes/__init__.py", line 381, in _init_
    self._handle = _dlopen(self._name, mode)
OSError: /home/samiw1/FBGEMM/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN6fbgemm8internal31compressed_indices_remap_avx512IiLb1EEEviPKT_PKiS4_PKfPS2_S9_Pf
```

Reviewed By: jspark1105

Differential Revision: D29190750

fbshipit-source-id: 78a9d8beebacb1d644ebd7de80087eb5721bc160