Re-apply "D18566687: [fbgemm] Fix the OSS build issue for FP16Benchmark when MKL/BLAS is not available" (#200)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/200

Original commit changeset: d0210b52d9e6

The original Diff D18566687 is reverted in D18571147. However, that Diff is not the real culprit for the OSS build failure.

The reason is in https://github.com/pytorch/FBGEMM/pull/195, we add the missing entry `src/FbgemmSpConv.cc` in CMakeLists.txt, which triggered more signals in OSS tests:
```
/root/project/src/FbgemmSpConv.cc:328:9: error: converting to 'std::vector<std::tuple<void (*)(const float*, float*, long unsigned int, const short unsigned int*, long unsigned int), int, int, int, int>, std::allocator<std::tuple<void (*)(const float*, float*, long unsigned int, const short unsigned int*, long unsigned int), int, int, int, int> > >::value_type {aka std::tuple<void (*)(const float*, float*, long unsigned int, const short unsigned int*, long unsigned int), int, int, int, int>}' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {void (*&)(const float*, float*, long unsigned int, const short unsigned int*, long unsigned int), int, int&, int&, int&}; <template-parameter-2-2> = void; _Elements = {void (*)(const float*, float*, long unsigned int, const short unsigned int*, long unsigned int), int, int, int, int}]'
         to_exec.push_back({sgemms[ky][kx],
         ^
```

The issue is quickly fixed in
https://github.com/pytorch/FBGEMM/pull/197, by using `make_tuple` to create the tuples.

Reviewed By: jspark1105

Differential Revision: D18575250

fbshipit-source-id: 69156ce30cab879a1d46519dc7997ce13d87a1bf