Fix OSS build and run issues
Summary:
Fix the OSS build issues of FBGEMM_GPU reported by Jiong Gong from Intel:
```
$ python test/split_table_batched_embeddings_test.py
Traceback (most recent call last):
  File "test/split_table_batched_embeddings_test.py", line 12, in <module>
    import fbgemm_gpu.split_table_batched_embeddings_ops as split_table_batched_embeddings_ops
ImportError: dynamic module does not define module export function (PyInit_fbgemm_gpu)
```

The PT ops in FBGEMM_GPU are registered with TorchScript custom ops:
https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html

However, currently we can only use local "*.so" file instead of install it in Python dependency folder (e.g., ~/miniconda3/lib/python3.8/site-packages). Otherwise, it reports "ImportError: dynamic module does not define module export function (PyInit_fbgemm_gpu)" error. TODO: figure out the way to automatically load *.so file when installing FBGEMM_GPU in Python dependency folder.

The OSS issue is caused by the ambiguity of "import fbgemm_gpu" under fbgemm_gpu folder. It can refer to load "fbgemm_gpu.so", or import the Python files in "fbgemm_gpu" folder. By renaming the so file to "fbgemm_gpu_py.so", we bypass this issue.

Differential Revision: D27132794

fbshipit-source-id: e694ef39d483b51aa4a5a665b65c4daa09e56095