Pin MarkupSafe>=3.0.0 for Python 3.14 compatibility (#5433)
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/2405

Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/5433

Fix CI failure on Python 3.14 caused by MarkupSafe 2.1.5 circular import error.

The jinja2 dependency was pulling in MarkupSafe 2.1.5, which has an initialization issue with Python 3.14:
```
AttributeError: partially initialized module 'markupsafe' has no attribute 'Markup' (most likely due to a circular import)
SystemError: initialization of _speedups raised unreported exception
```

MarkupSafe 3.0.0+ includes proper Python 3.14 support and resolves this compatibility issue.

Reviewed By: q10

Differential Revision: D94448875

fbshipit-source-id: 8f0058de6701548ba7a0ed11cc37d57e40e09a59