Fix dispatch_macros.h being moved (#2841)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/2841

 `dispatch_macros.h` was moved to `utils/dispatch_macros.h' in D59694995. Not all were updated.

OSS errror:
```
/__w/FBGEMM/FBGEMM/fbgemm_gpu/include/fbgemm_gpu/permute_multi_embedding_function.h:16:10: fatal error: 'fbgemm_gpu/dispatch_macros.h' file not found
```

Differential Revision: D59707132