use total_L is None for dense_to_jagged + fix linter errors (#2599)
Summary:

# Could not guard on data-dependent expression Ne(u0, 0)

```
RuntimeError: Failed running call_function fbgemm.dense_to_jagged(*(FakeTensor(..., device='cuda:0', size=(s1, 2540, 512), dtype=torch.bfloat16), [FakeTensor(..., device='cuda:0', size=(s1 + 1,), dtype=torch.int64)]), **{'total_L': None}):
Could not guard on data-dependent expression Ne(u0, 0) (unhinted: Ne(u0, 0)).  (Size-like symbols: u0)
ATTENTION: guard_size_oblivious would fix the error, evaluating expression to True.
Maybe you need to add guard_size_oblivious to framework code, see doc below for more guidance.
Potential framework code culprit (scroll up for full backtrace):
  File "/mnt/xarfuse/uid-119376/a7f0c177-seed-nspid4026531836_cgpid3083025-ns-4026531841/fbgemm_gpu/sparse_ops.py", line 467, in dense_to_jagged_forward
    if not total_L:


User Stack (most recent call last):
  (snipped, see stack below for prefix)
  File "<eval_with_key>.82", line 424, in forward
    dense_to_jagged = torch.ops.fbgemm.dense_to_jagged(matmul_22, [asynchronous_complete_cumsum_9], total_L = None);  matmul_22 = None
```

Reviewed By: frank-wei

Differential Revision: D57465638