Fix f8f8bf16_lite quantize op input in `quantize_and_compute` (#3667)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/3667

X-link: https://github.com/facebookresearch/FBGEMM/pull/745

A minor fix for trt-llm cudaCoreGemm `cuda_lite` op in quantize_bench script.

when testing with `--bench_quantize` detected a failure with input

```
...
tree/deeplearning/fbgemm/fbgemm_gpu/experimental/gen_ai/bench/quantize_ops.py", line 797, in quantize_and_compute
    return self.compute(xq, wq, x_scale * w_scale)
TypeError: FP8LiteGemm.compute() missing 1 required positional argument: 'w_scale'
```

Reviewed By: jwfromm

Differential Revision: D69272912

fbshipit-source-id: c184954b4d2d1543277a9e56ac899534597a56e6