Make split_embedding_weights_with_scale_bias(2) scriptable (#1988)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/1988

Some infra like xlweights is using `split_embedding_weights_with_scale_bias` for torch scripted modules,
mode==2 fails in torch script due to `.view(torch.float16)`
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/mnt/xarfuse/uid-128598/ebee08ee-seed-nspid4026531836_cgpid9192421-ns-4026531840/fbgemm_gpu/split_table_batched_embeddings_ops_inference.py", line 1202, in split_embedding_weights_with_scale_bias
                            (
                                weights_shifts[:, self.scale_bias_size_in_bytes :],
                                weights_shifts[:, : self.scale_bias_size_in_bytes // 2].view(torch.float16),
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                weights_shifts[
                                    :,
```

Differential Revision:
D48879020

Privacy Context Container: L1138451

fbshipit-source-id: cd69a1045b44b5475a19edc7381a52dfebf4f022