Update Utils.h (#1233)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/1233

Extract asmjit/asmjit.h usages into a separate header file and make sure it is not called from PyTorch directly.

This Diff/PR is to unblock the FBGEMM third party upgrade in PyTorch (e.g.,  https://github.com/pytorch/pytorch/pull/82396), where it consistantly reports the <asmjit/asmjit.h> imports error (https://github.com/pytorch/FBGEMM/issues/1227):

```
[ 40%] Building C object confu-deps/XNNPACK/CMakeFiles/all_microkernels.dir/src/qs8-gemm/gen/4x4-minmax-fp32-scalar-imagic.c.o
In file included from /var/lib/jenkins/workspace/caffe2/quantization/server/group_norm_dnnlowp_op_avx2.cc:10:
In file included from /var/lib/jenkins/workspace/third_party/fbgemm/include/fbgemm/QuantUtils.h:6:
/var/lib/jenkins/workspace/third_party/fbgemm/include/fbgemm/./Utils.h:18:10: fatal error: 'asmjit/asmjit.h' file not found
#include <asmjit/asmjit.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [caffe2/quantization/server/CMakeFiles/caffe2_dnnlowp_avx2_ops.dir/build.make:104: caffe2/quantization/server/CMakeFiles/caffe2_dnnlowp_avx2_ops.dir/group_norm_dnnlowp_op_avx2.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/qc8-igemm/gen/4x16c8-minmax-fp32-avx512skx.c.o

```

This is because we don't have the direct asmjit dependency in PyTorch. The workaround is to spin off Utils.h to SimdUtils.h where the original Utils.h included in PyTorch files doesn't have asmjit.h dependency any longer.

Reviewed By: jasonjk-park, jiyuanzFB

Differential Revision: D38341763

fbshipit-source-id: 77bf92206d350b220dfe13d7a5488713b33e7b47