Add header to fix PRIu64 error (#2234)
Summary:

ROCm builds failed with the following errors on CI https://github.com/pytorch/FBGEMM/actions/runs/7329180569. 

```
/__w/FBGEMM/FBGEMM/fbgemm_gpu/src/topology_utils_hip.cpp:55:15: error: expected ')'
        "%04" PRIu64 ":%02" PRIu64 ":%02" PRIu64 ".%0" PRIu64,
              ^
/__w/FBGEMM/FBGEMM/fbgemm_gpu/src/topology_utils_hip.cpp:53:12: note: to match this '('
    sprintf(
           ^
1 error generated when compiling for gfx908.
CMake Error at fbgemm_gpu_py_generated_topology_utils_hip.cpp.o.cmake:200 (message):
  Error generating file
  /__w/FBGEMM/FBGEMM/fbgemm_gpu/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/fbgemm_gpu_py.dir/src/./fbgemm_gpu_py_generated_topology_utils_hip.cpp.o
```

This is probably due to a header being removed in the latest torch nightly. This diff explicitly adds the header.

Differential Revision: D52420862