Back out "Move `transpose_simd` to TransposeUtils.cc"
Summary:
This breaks the pytorch_bazel_test:
error: undefined reference to 'fbgemm::transpose_simd

Original commit changeset: 5ec1c8261a81

Reviewed By: yns88

Differential Revision: D20971404

fbshipit-source-id: 43dd2030528747d073969df2e6a012c65716b713