iOS App Champion | unblock Xcode 15 build with issues in fbgemm (#1915)
Summary:
## tl;dr
To address issues in
https://www.internalfb.com/intern/sandcastle/job/31525198400891768/
https://internalfb.com/intern/sandcastle/job/36028798030097644/artifact/actionlog.36028808645023206.log?selectedLines=296-305-1-20
{P803212711}

## Context
Xcode 15 is the next major release from Apple, with the next version SDK of macOS and iOS. It's planned to be released in September, and we schedule these `xcodestaging` to see if the new SDK breaks builds.

From the build log, we see the following errors in these files. So removing those lines since these are no longer required by C++ 17 indeed.
```
error: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Werror,-Wdeprecated]
```

Differential Revision: D48030434

Pulled By: sodastsai

fbshipit-source-id: 074f4b5c6508ceb4d548bddd4dd53df55c98d6d7