Make CowClipDefinition and CounterBasedRegularizationDefinition hashable (#2539)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/2539

Mutable dataclass fails at https://fburl.com/code/dksx3yjo due to
```
TypeError: unhashable type: 'CowClipDefinition'
```
https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-350x_eb6_64_2560_0311_optim_eps_cowclip-a653e81151?job_attempt=0&version=0&env=PRODUCTION

Making these definitions `frozen` fixes the problem.

Reviewed By: spcyppt

Differential Revision: D56643198

fbshipit-source-id: bc8e864168482c2a1ab6c08fb9dec568676d8f7b